name: ASM/C cmake build

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup nasm
      run: choco install nasm

    - name: Verify nasm
      run: refreshenv | nasm -v

    - name: Configure CMake
      run: mkdir build | cmake -B ${{github.workspace}}/build -G "Ninja"

    - name: Build
      run: cmake --build ${{github.workspace}}/build
